"""upd models

Revision ID: 28fb7b6b7454
Revises: 0be695a68370
Create Date: 2025-09-29 16:01:55.298601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28fb7b6b7454"
down_revision: Union[str, None] = "0be695a68370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "missions",
        "status",
        existing_type=postgresql.ENUM(
            "assigned",
            "in_progress",
            "completed",
            "report_pending",
            "verified",
            "cancelled",
            name="missionstatus",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "missions",
        "status",
        existing_type=postgresql.ENUM(
            "assigned",
            "in_progress",
            "completed",
            "report_pending",
            "verified",
            "cancelled",
            name="missionstatus",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
