"""make user_roles.id auto-increment

Revision ID: 538ccc8df13c
Revises: fb7971b0ee4c
Create Date: 2025-09-28 22:10:53.396172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "538ccc8df13c"
down_revision: Union[str, None] = "fb7971b0ee4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "user_roles",
        existing_comment="Composite PK + check constraint",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "user_roles",
        "Composite PK + check constraint",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###
