"""user role model upd

Revision ID: b0c3abf11519
Revises: 538ccc8df13c
Create Date: 2025-09-28 22:31:40.624069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0c3abf11519"
down_revision: Union[str, None] = "538ccc8df13c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.add_column(
        "users", sa.Column("role", sa.String(length=20), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.create_table(
        "user_roles",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "role", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_roles_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role", name=op.f("user_roles_pkey")),
    )
    # ### end Alembic commands ###
